# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Which Translation?
email: contact@whichtranslation.com
description: > # this means to ignore newlines until "baseurl:"
  Because not everyone can be an omniglot.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://whichtranslation.com" # the base hostname & protocol for your site
twitter_username: whichtrans
github_username:  whichtranslation
collections:
  authors:
    output: true
    permalink: /:path:/

# Build settings
markdown: kramdown
plugins:
  - jekyll-sitemap
